
package io.renren.common.agvs;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AGVS_IServiceForView", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AGVSIServiceForView {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "ModifyFactory", action = "http://tempuri.org/AGVS_IServiceForView/ModifyFactory")
    @WebResult(name = "ModifyFactoryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ModifyFactory", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifyFactory")
    @ResponseWrapper(localName = "ModifyFactoryResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifyFactoryResponse")
    public Boolean modifyFactory(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        Factory name);

    /**
     * 
     * @param companyID
     * @return
     *     returns io.renren.common.agvs.ArrayOfFactory
     */
    @WebMethod(operationName = "GetAllFactoryInCompany", action = "http://tempuri.org/AGVS_IServiceForView/GetAllFactoryInCompany")
    @WebResult(name = "GetAllFactoryInCompanyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAllFactoryInCompany", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetAllFactoryInCompany")
    @ResponseWrapper(localName = "GetAllFactoryInCompanyResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetAllFactoryInCompanyResponse")
    public ArrayOfFactory getAllFactoryInCompany(
        @WebParam(name = "CompanyID", targetNamespace = "http://tempuri.org/")
        Integer companyID);

    /**
     * 
     * @param companyID
     * @param factoryID
     * @return
     *     returns io.renren.common.agvs.Factory
     */
    @WebMethod(operationName = "GetFactory", action = "http://tempuri.org/AGVS_IServiceForView/GetFactory")
    @WebResult(name = "GetFactoryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetFactory", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetFactory")
    @ResponseWrapper(localName = "GetFactoryResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetFactoryResponse")
    public Factory getFactory(
        @WebParam(name = "CompanyID", targetNamespace = "http://tempuri.org/")
        Integer companyID,
        @WebParam(name = "FactoryID", targetNamespace = "http://tempuri.org/")
        Integer factoryID);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "AddWorkArea", action = "http://tempuri.org/AGVS_IServiceForView/AddWorkArea")
    @WebResult(name = "AddWorkAreaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddWorkArea", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddWorkArea")
    @ResponseWrapper(localName = "AddWorkAreaResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddWorkAreaResponse")
    public Boolean addWorkArea(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name);

    /**
     * 
     * @param companyID
     * @param factoryID
     * @param workAreaID
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DelWorkArea", action = "http://tempuri.org/AGVS_IServiceForView/DelWorkArea")
    @WebResult(name = "DelWorkAreaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DelWorkArea", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelWorkArea")
    @ResponseWrapper(localName = "DelWorkAreaResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelWorkAreaResponse")
    public Boolean delWorkArea(
        @WebParam(name = "CompanyID", targetNamespace = "http://tempuri.org/")
        Integer companyID,
        @WebParam(name = "FactoryID", targetNamespace = "http://tempuri.org/")
        Integer factoryID,
        @WebParam(name = "WorkAreaID", targetNamespace = "http://tempuri.org/")
        Integer workAreaID);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "ModifyWorkArea", action = "http://tempuri.org/AGVS_IServiceForView/ModifyWorkArea")
    @WebResult(name = "ModifyWorkAreaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ModifyWorkArea", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifyWorkArea")
    @ResponseWrapper(localName = "ModifyWorkAreaResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifyWorkAreaResponse")
    public Boolean modifyWorkArea(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name);

    /**
     * 
     * @return
     *     returns io.renren.common.agvs.ArrayOfWorkAreaName
     */
    @WebMethod(operationName = "GetAllWorkArea", action = "http://tempuri.org/AGVS_IServiceForView/GetAllWorkArea")
    @WebResult(name = "GetAllWorkAreaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAllWorkArea", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetAllWorkArea")
    @ResponseWrapper(localName = "GetAllWorkAreaResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetAllWorkAreaResponse")
    public ArrayOfWorkAreaName getAllWorkArea();

    /**
     * 
     * @param companyID
     * @return
     *     returns io.renren.common.agvs.ArrayOfWorkAreaName
     */
    @WebMethod(operationName = "GetAllWorkAreaInCompany", action = "http://tempuri.org/AGVS_IServiceForView/GetAllWorkAreaInCompany")
    @WebResult(name = "GetAllWorkAreaInCompanyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAllWorkAreaInCompany", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetAllWorkAreaInCompany")
    @ResponseWrapper(localName = "GetAllWorkAreaInCompanyResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetAllWorkAreaInCompanyResponse")
    public ArrayOfWorkAreaName getAllWorkAreaInCompany(
        @WebParam(name = "CompanyID", targetNamespace = "http://tempuri.org/")
        Integer companyID);

    /**
     * 
     * @param companyID
     * @param factoryID
     * @return
     *     returns io.renren.common.agvs.ArrayOfWorkAreaName
     */
    @WebMethod(operationName = "GetAllWorkAreaInFactory", action = "http://tempuri.org/AGVS_IServiceForView/GetAllWorkAreaInFactory")
    @WebResult(name = "GetAllWorkAreaInFactoryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAllWorkAreaInFactory", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetAllWorkAreaInFactory")
    @ResponseWrapper(localName = "GetAllWorkAreaInFactoryResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetAllWorkAreaInFactoryResponse")
    public ArrayOfWorkAreaName getAllWorkAreaInFactory(
        @WebParam(name = "CompanyID", targetNamespace = "http://tempuri.org/")
        Integer companyID,
        @WebParam(name = "FactoryID", targetNamespace = "http://tempuri.org/")
        Integer factoryID);

    /**
     * 
     * @param companyID
     * @param factoryID
     * @param workAreaID
     * @return
     *     returns io.renren.common.agvs.WorkAreaName
     */
    @WebMethod(operationName = "GetWorkArea", action = "http://tempuri.org/AGVS_IServiceForView/GetWorkArea")
    @WebResult(name = "GetWorkAreaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetWorkArea", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetWorkArea")
    @ResponseWrapper(localName = "GetWorkAreaResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetWorkAreaResponse")
    public WorkAreaName getWorkArea(
        @WebParam(name = "CompanyID", targetNamespace = "http://tempuri.org/")
        Integer companyID,
        @WebParam(name = "FactoryID", targetNamespace = "http://tempuri.org/")
        Integer factoryID,
        @WebParam(name = "WorkAreaID", targetNamespace = "http://tempuri.org/")
        Integer workAreaID);

    /**
     * 
     * @param strBlackBox
     */
    @WebMethod(operationName = "WriteBlackBoxFile", action = "http://tempuri.org/AGVS_IServiceForView/WriteBlackBoxFile")
    @Oneway
    @RequestWrapper(localName = "WriteBlackBoxFile", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.WriteBlackBoxFile")
    public void writeBlackBoxFile(
        @WebParam(name = "strBlackBox", targetNamespace = "http://tempuri.org/")
        String strBlackBox);

    /**
     * 
     * @return
     *     returns io.renren.common.agvs.ArrayOfAGVOrderMessage
     */
    @WebMethod(operationName = "GetAllWorkAreaOrderArray", action = "http://tempuri.org/AGVS_IServiceForView/GetAllWorkAreaOrderArray")
    @WebResult(name = "GetAllWorkAreaOrderArrayResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAllWorkAreaOrderArray", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetAllWorkAreaOrderArray")
    @ResponseWrapper(localName = "GetAllWorkAreaOrderArrayResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetAllWorkAreaOrderArrayResponse")
    public ArrayOfAGVOrderMessage getAllWorkAreaOrderArray();

    /**
     * 
     * @return
     *     returns io.renren.common.agvs.ArrayOfAGVStatusMessage
     */
    @WebMethod(operationName = "GetAllWorkAreaAGVStatusArray", action = "http://tempuri.org/AGVS_IServiceForView/GetAllWorkAreaAGVStatusArray")
    @WebResult(name = "GetAllWorkAreaAGVStatusArrayResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAllWorkAreaAGVStatusArray", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetAllWorkAreaAGVStatusArray")
    @ResponseWrapper(localName = "GetAllWorkAreaAGVStatusArrayResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetAllWorkAreaAGVStatusArrayResponse")
    public ArrayOfAGVStatusMessage getAllWorkAreaAGVStatusArray();

    /**
     * 
     * @return
     *     returns io.renren.common.agvs.ArrayOfEquipmentData
     */
    @WebMethod(operationName = "GetAllWorkAreaEquipmentArray", action = "http://tempuri.org/AGVS_IServiceForView/GetAllWorkAreaEquipmentArray")
    @WebResult(name = "GetAllWorkAreaEquipmentArrayResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAllWorkAreaEquipmentArray", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetAllWorkAreaEquipmentArray")
    @ResponseWrapper(localName = "GetAllWorkAreaEquipmentArrayResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetAllWorkAreaEquipmentArrayResponse")
    public ArrayOfEquipmentData getAllWorkAreaEquipmentArray();

    /**
     * 
     * @return
     *     returns io.renren.common.agvs.ArrayOfChargeParkMessage
     */
    @WebMethod(operationName = "GetAllWorkAreaStationChargeParkArray", action = "http://tempuri.org/AGVS_IServiceForView/GetAllWorkAreaStationChargeParkArray")
    @WebResult(name = "GetAllWorkAreaStationChargeParkArrayResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAllWorkAreaStationChargeParkArray", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetAllWorkAreaStationChargeParkArray")
    @ResponseWrapper(localName = "GetAllWorkAreaStationChargeParkArrayResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetAllWorkAreaStationChargeParkArrayResponse")
    public ArrayOfChargeParkMessage getAllWorkAreaStationChargeParkArray();

    /**
     * 
     * @param uType
     * @param uEquipmentID
     * @return
     *     returns io.renren.common.agvs.WorkAreaName
     */
    @WebMethod(operationName = "GetWorkAreaByEquipmentIDAndType", action = "http://tempuri.org/AGVS_IServiceForView/GetWorkAreaByEquipmentIDAndType")
    @WebResult(name = "GetWorkAreaByEquipmentIDAndTypeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetWorkAreaByEquipmentIDAndType", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetWorkAreaByEquipmentIDAndType")
    @ResponseWrapper(localName = "GetWorkAreaByEquipmentIDAndTypeResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetWorkAreaByEquipmentIDAndTypeResponse")
    public WorkAreaName getWorkAreaByEquipmentIDAndType(
        @WebParam(name = "uEquipmentID", targetNamespace = "http://tempuri.org/")
        Integer uEquipmentID,
        @WebParam(name = "uType", targetNamespace = "http://tempuri.org/")
        Integer uType);

    /**
     * 
     * @param chargeParkList
     * @param name
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "AddChargeParkList", action = "http://tempuri.org/AGVS_IServiceForView/AddChargeParkList")
    @WebResult(name = "AddChargeParkListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddChargeParkList", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddChargeParkList")
    @ResponseWrapper(localName = "AddChargeParkListResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddChargeParkListResponse")
    public Boolean addChargeParkList(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "chargeParkList", targetNamespace = "http://tempuri.org/")
        ArrayOfChargeParkMessage chargeParkList);

    /**
     * 
     * @param chargeParkList
     * @param name
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "AddChargePark", action = "http://tempuri.org/AGVS_IServiceForView/AddChargePark")
    @WebResult(name = "AddChargeParkResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddChargePark", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddChargePark")
    @ResponseWrapper(localName = "AddChargeParkResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddChargeParkResponse")
    public Boolean addChargePark(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "chargeParkList", targetNamespace = "http://tempuri.org/")
        ChargeParkMessage chargeParkList);

    /**
     * 
     * @param name
     * @param stationID
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DelChargePark", action = "http://tempuri.org/AGVS_IServiceForView/DelChargePark")
    @WebResult(name = "DelChargeParkResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DelChargePark", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelChargePark")
    @ResponseWrapper(localName = "DelChargeParkResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelChargeParkResponse")
    public Boolean delChargePark(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "StationID", targetNamespace = "http://tempuri.org/")
        Integer stationID);

    /**
     * 
     * @param curChargePark
     * @param name
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "ModifyChargePark", action = "http://tempuri.org/AGVS_IServiceForView/ModifyChargePark")
    @WebResult(name = "ModifyChargeParkResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ModifyChargePark", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifyChargePark")
    @ResponseWrapper(localName = "ModifyChargeParkResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifyChargeParkResponse")
    public Boolean modifyChargePark(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "CurChargePark", targetNamespace = "http://tempuri.org/")
        ChargeParkMessage curChargePark);

    /**
     * 
     * @param curChargePark
     * @param name
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "ModifyChargeParkByStationID", action = "http://tempuri.org/AGVS_IServiceForView/ModifyChargeParkByStationID")
    @WebResult(name = "ModifyChargeParkByStationIDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ModifyChargeParkByStationID", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifyChargeParkByStationID")
    @ResponseWrapper(localName = "ModifyChargeParkByStationIDResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifyChargeParkByStationIDResponse")
    public Boolean modifyChargeParkByStationID(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "CurChargePark", targetNamespace = "http://tempuri.org/")
        ChargeParkMessage curChargePark);

    /**
     * 
     * @param chargeID
     * @param name
     * @param parkID
     * @param stationID
     * @return
     *     returns io.renren.common.agvs.ChargeParkMessage
     */
    @WebMethod(operationName = "GetChargePark", action = "http://tempuri.org/AGVS_IServiceForView/GetChargePark")
    @WebResult(name = "GetChargeParkResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetChargePark", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetChargePark")
    @ResponseWrapper(localName = "GetChargeParkResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetChargeParkResponse")
    public ChargeParkMessage getChargePark(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "StationID", targetNamespace = "http://tempuri.org/")
        Integer stationID,
        @WebParam(name = "ParkID", targetNamespace = "http://tempuri.org/")
        Integer parkID,
        @WebParam(name = "ChargeID", targetNamespace = "http://tempuri.org/")
        Integer chargeID);

    /**
     * 
     * @param name
     * @return
     *     returns io.renren.common.agvs.ArrayOfChargeParkMessage
     */
    @WebMethod(operationName = "GetChargeParkList", action = "http://tempuri.org/AGVS_IServiceForView/GetChargeParkList")
    @WebResult(name = "GetChargeParkListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetChargeParkList", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetChargeParkList")
    @ResponseWrapper(localName = "GetChargeParkListResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetChargeParkListResponse")
    public ArrayOfChargeParkMessage getChargeParkList(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name);

    /**
     * 
     * @param name
     * @param type
     * @param uChargeID
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "AddSystemLevelEquipment", action = "http://tempuri.org/AGVS_IServiceForView/AddSystemLevelEquipment")
    @WebResult(name = "AddSystemLevelEquipmentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddSystemLevelEquipment", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddSystemLevelEquipment")
    @ResponseWrapper(localName = "AddSystemLevelEquipmentResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddSystemLevelEquipmentResponse")
    public Boolean addSystemLevelEquipment(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "uChargeID", targetNamespace = "http://tempuri.org/")
        Integer uChargeID,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        Integer type);

    /**
     * 
     * @param type
     * @param uChargeID
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DelSystemLevelEquipment", action = "http://tempuri.org/AGVS_IServiceForView/DelSystemLevelEquipment")
    @WebResult(name = "DelSystemLevelEquipmentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DelSystemLevelEquipment", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelSystemLevelEquipment")
    @ResponseWrapper(localName = "DelSystemLevelEquipmentResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelSystemLevelEquipmentResponse")
    public Boolean delSystemLevelEquipment(
        @WebParam(name = "uChargeID", targetNamespace = "http://tempuri.org/")
        Integer uChargeID,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        Integer type);

    /**
     * 
     * @param orderMessage
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "AddOrder", action = "http://tempuri.org/AGVS_IServiceForView/AddOrder")
    @WebResult(name = "AddOrderResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddOrder", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddOrder")
    @ResponseWrapper(localName = "AddOrderResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddOrderResponse")
    public Boolean addOrder(
        @WebParam(name = "OrderMessage", targetNamespace = "http://tempuri.org/")
        AGVOrderMessage orderMessage);

    /**
     * 
     * @param orderID
     * @param name
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DelOrder", action = "http://tempuri.org/AGVS_IServiceForView/DelOrder")
    @WebResult(name = "DelOrderResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DelOrder", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelOrder")
    @ResponseWrapper(localName = "DelOrderResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelOrderResponse")
    public Boolean delOrder(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "OrderID", targetNamespace = "http://tempuri.org/")
        Integer orderID);

    /**
     * 
     * @param orderID
     * @param name
     * @return
     *     returns io.renren.common.agvs.AGVOrderMessage
     */
    @WebMethod(operationName = "GetOrder", action = "http://tempuri.org/AGVS_IServiceForView/GetOrder")
    @WebResult(name = "GetOrderResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetOrder", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetOrder")
    @ResponseWrapper(localName = "GetOrderResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetOrderResponse")
    public AGVOrderMessage getOrder(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "OrderID", targetNamespace = "http://tempuri.org/")
        Integer orderID);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "GetOrderMaxID", action = "http://tempuri.org/AGVS_IServiceForView/GetOrderMaxID")
    @WebResult(name = "GetOrderMaxIDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetOrderMaxID", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetOrderMaxID")
    @ResponseWrapper(localName = "GetOrderMaxIDResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetOrderMaxIDResponse")
    public Integer getOrderMaxID(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name);

    /**
     * 
     * @param name
     * @return
     *     returns io.renren.common.agvs.ArrayOfAGVOrderMessage
     */
    @WebMethod(operationName = "GetOrderArray", action = "http://tempuri.org/AGVS_IServiceForView/GetOrderArray")
    @WebResult(name = "GetOrderArrayResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetOrderArray", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetOrderArray")
    @ResponseWrapper(localName = "GetOrderArrayResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetOrderArrayResponse")
    public ArrayOfAGVOrderMessage getOrderArray(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name);

    /**
     * 
     * @param name
     * @param agvStep
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "AddStep", action = "http://tempuri.org/AGVS_IServiceForView/AddStep")
    @WebResult(name = "AddStepResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddStep", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddStep")
    @ResponseWrapper(localName = "AddStepResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddStepResponse")
    public Boolean addStep(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "AGVStep", targetNamespace = "http://tempuri.org/")
        AGVStepMessage agvStep);

    /**
     * 
     * @param name
     * @param agvStep
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DelStep", action = "http://tempuri.org/AGVS_IServiceForView/DelStep")
    @WebResult(name = "DelStepResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DelStep", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelStep")
    @ResponseWrapper(localName = "DelStepResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelStepResponse")
    public Boolean delStep(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "AGVStep", targetNamespace = "http://tempuri.org/")
        AGVStepMessage agvStep);

    /**
     * 
     * @param name
     * @param agvStep
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "ModifyStep", action = "http://tempuri.org/AGVS_IServiceForView/ModifyStep")
    @WebResult(name = "ModifyStepResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ModifyStep", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifyStep")
    @ResponseWrapper(localName = "ModifyStepResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifyStepResponse")
    public Boolean modifyStep(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "AGVStep", targetNamespace = "http://tempuri.org/")
        AGVStepMessage agvStep);

    /**
     * 
     * @param orderMessage
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "AddStandardOrder", action = "http://tempuri.org/AGVS_IServiceForView/AddStandardOrder")
    @WebResult(name = "AddStandardOrderResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddStandardOrder", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddStandardOrder")
    @ResponseWrapper(localName = "AddStandardOrderResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddStandardOrderResponse")
    public Boolean addStandardOrder(
        @WebParam(name = "OrderMessage", targetNamespace = "http://tempuri.org/")
        AGVOrderMessage orderMessage);

    /**
     * 
     * @param number
     * @param name
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DelStandardOrder", action = "http://tempuri.org/AGVS_IServiceForView/DelStandardOrder")
    @WebResult(name = "DelStandardOrderResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DelStandardOrder", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelStandardOrder")
    @ResponseWrapper(localName = "DelStandardOrderResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelStandardOrderResponse")
    public Boolean delStandardOrder(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "Number", targetNamespace = "http://tempuri.org/")
        Integer number);

    /**
     * 
     * @param number
     * @param name
     * @return
     *     returns io.renren.common.agvs.AGVOrderMessage
     */
    @WebMethod(operationName = "GetStandardOrder", action = "http://tempuri.org/AGVS_IServiceForView/GetStandardOrder")
    @WebResult(name = "GetStandardOrderResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStandardOrder", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetStandardOrder")
    @ResponseWrapper(localName = "GetStandardOrderResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetStandardOrderResponse")
    public AGVOrderMessage getStandardOrder(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "Number", targetNamespace = "http://tempuri.org/")
        Integer number);

    /**
     * 
     * @param name
     * @return
     *     returns io.renren.common.agvs.ArrayOfAGVOrderMessage
     */
    @WebMethod(operationName = "GetStandardOrderArray", action = "http://tempuri.org/AGVS_IServiceForView/GetStandardOrderArray")
    @WebResult(name = "GetStandardOrderArrayResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStandardOrderArray", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetStandardOrderArray")
    @ResponseWrapper(localName = "GetStandardOrderArrayResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetStandardOrderArrayResponse")
    public ArrayOfAGVOrderMessage getStandardOrderArray(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name);

    /**
     * 
     * @param name
     * @param curOrderMessage
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "ModifyStandardOrder", action = "http://tempuri.org/AGVS_IServiceForView/ModifyStandardOrder")
    @WebResult(name = "ModifyStandardOrderResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ModifyStandardOrder", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifyStandardOrder")
    @ResponseWrapper(localName = "ModifyStandardOrderResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifyStandardOrderResponse")
    public Boolean modifyStandardOrder(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "CurOrderMessage", targetNamespace = "http://tempuri.org/")
        AGVOrderMessage curOrderMessage);

    /**
     * 
     * @param name
     * @param agvStep
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "AddStandardStep", action = "http://tempuri.org/AGVS_IServiceForView/AddStandardStep")
    @WebResult(name = "AddStandardStepResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddStandardStep", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddStandardStep")
    @ResponseWrapper(localName = "AddStandardStepResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddStandardStepResponse")
    public Boolean addStandardStep(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "AGVStep", targetNamespace = "http://tempuri.org/")
        AGVStepMessage agvStep);

    /**
     * 
     * @param name
     * @param agvStep
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DelStandardStep", action = "http://tempuri.org/AGVS_IServiceForView/DelStandardStep")
    @WebResult(name = "DelStandardStepResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DelStandardStep", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelStandardStep")
    @ResponseWrapper(localName = "DelStandardStepResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelStandardStepResponse")
    public Boolean delStandardStep(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "AGVStep", targetNamespace = "http://tempuri.org/")
        AGVStepMessage agvStep);

    /**
     * 
     * @param name
     * @param agvStep
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "ModifyStandardStep", action = "http://tempuri.org/AGVS_IServiceForView/ModifyStandardStep")
    @WebResult(name = "ModifyStandardStepResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ModifyStandardStep", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifyStandardStep")
    @ResponseWrapper(localName = "ModifyStandardStepResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifyStandardStepResponse")
    public Boolean modifyStandardStep(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "AGVStep", targetNamespace = "http://tempuri.org/")
        AGVStepMessage agvStep);

    /**
     * 
     * @param name
     * @param uOrderNumber
     * @return
     *     returns io.renren.common.agvs.ArrayOfAGVStepMessage
     */
    @WebMethod(operationName = "GetStandardStepArray", action = "http://tempuri.org/AGVS_IServiceForView/GetStandardStepArray")
    @WebResult(name = "GetStandardStepArrayResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStandardStepArray", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetStandardStepArray")
    @ResponseWrapper(localName = "GetStandardStepArrayResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetStandardStepArrayResponse")
    public ArrayOfAGVStepMessage getStandardStepArray(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "uOrderNumber", targetNamespace = "http://tempuri.org/")
        Integer uOrderNumber);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "GetStandardOrderColumnCount", action = "http://tempuri.org/AGVS_IServiceForView/GetStandardOrderColumnCount")
    @WebResult(name = "GetStandardOrderColumnCountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStandardOrderColumnCount", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetStandardOrderColumnCount")
    @ResponseWrapper(localName = "GetStandardOrderColumnCountResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetStandardOrderColumnCountResponse")
    public Integer getStandardOrderColumnCount(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "AddRegisterCarrier", action = "http://tempuri.org/AGVS_IServiceForView/AddRegisterCarrier")
    @WebResult(name = "AddRegisterCarrierResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddRegisterCarrier", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddRegisterCarrier")
    @ResponseWrapper(localName = "AddRegisterCarrierResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddRegisterCarrierResponse")
    public Boolean addRegisterCarrier(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        AGVName name);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DelRegisterCarrier", action = "http://tempuri.org/AGVS_IServiceForView/DelRegisterCarrier")
    @WebResult(name = "DelRegisterCarrierResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DelRegisterCarrier", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelRegisterCarrier")
    @ResponseWrapper(localName = "DelRegisterCarrierResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelRegisterCarrierResponse")
    public Boolean delRegisterCarrier(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        AGVName name);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "ModifyCarrier", action = "http://tempuri.org/AGVS_IServiceForView/ModifyCarrier")
    @WebResult(name = "ModifyCarrierResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ModifyCarrier", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifyCarrier")
    @ResponseWrapper(localName = "ModifyCarrierResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifyCarrierResponse")
    public Boolean modifyCarrier(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        AGVName name);

    /**
     * 
     * @param name
     * @param id
     * @return
     *     returns io.renren.common.agvs.AGVName
     */
    @WebMethod(operationName = "GetCarrier", action = "http://tempuri.org/AGVS_IServiceForView/GetCarrier")
    @WebResult(name = "GetCarrierResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCarrier", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetCarrier")
    @ResponseWrapper(localName = "GetCarrierResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetCarrierResponse")
    public AGVName getCarrier(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "ID", targetNamespace = "http://tempuri.org/")
        Integer id);

    /**
     * 
     * @param name
     * @return
     *     returns io.renren.common.agvs.ArrayOfAGVName
     */
    @WebMethod(operationName = "GetCarrierArray", action = "http://tempuri.org/AGVS_IServiceForView/GetCarrierArray")
    @WebResult(name = "GetCarrierArrayResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCarrierArray", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetCarrierArray")
    @ResponseWrapper(localName = "GetCarrierArrayResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetCarrierArrayResponse")
    public ArrayOfAGVName getCarrierArray(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name);

    /**
     * 
     * @param name
     * @return
     *     returns io.renren.common.agvs.ArrayOfAGVStatusMessage
     */
    @WebMethod(operationName = "GetCarrierStatusArray", action = "http://tempuri.org/AGVS_IServiceForView/GetCarrierStatusArray")
    @WebResult(name = "GetCarrierStatusArrayResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCarrierStatusArray", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetCarrierStatusArray")
    @ResponseWrapper(localName = "GetCarrierStatusArrayResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetCarrierStatusArrayResponse")
    public ArrayOfAGVStatusMessage getCarrierStatusArray(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name);

    /**
     * 
     * @param cluster
     * @param name
     */
    @WebMethod(operationName = "AddCluster", action = "http://tempuri.org/AGVS_IServiceForView/AddCluster")
    @Oneway
    @RequestWrapper(localName = "AddCluster", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddCluster")
    public void addCluster(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "Cluster", targetNamespace = "http://tempuri.org/")
        ClusterMessage cluster);

    /**
     * 
     * @param name
     * @param clusterID
     */
    @WebMethod(operationName = "DelCluster", action = "http://tempuri.org/AGVS_IServiceForView/DelCluster")
    @Oneway
    @RequestWrapper(localName = "DelCluster", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelCluster")
    public void delCluster(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "ClusterID", targetNamespace = "http://tempuri.org/")
        Integer clusterID);

    /**
     * 
     * @param cluster
     * @param name
     */
    @WebMethod(operationName = "ModifyCluster", action = "http://tempuri.org/AGVS_IServiceForView/ModifyCluster")
    @Oneway
    @RequestWrapper(localName = "ModifyCluster", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifyCluster")
    public void modifyCluster(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "Cluster", targetNamespace = "http://tempuri.org/")
        ClusterMessage cluster);

    /**
     * 
     * @param name
     * @return
     *     returns io.renren.common.agvs.ArrayOfClusterMessage
     */
    @WebMethod(operationName = "GetClusterArray", action = "http://tempuri.org/AGVS_IServiceForView/GetClusterArray")
    @WebResult(name = "GetClusterArrayResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetClusterArray", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetClusterArray")
    @ResponseWrapper(localName = "GetClusterArrayResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetClusterArrayResponse")
    public ArrayOfClusterMessage getClusterArray(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "GetClusterColumnCount", action = "http://tempuri.org/AGVS_IServiceForView/GetClusterColumnCount")
    @WebResult(name = "GetClusterColumnCountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetClusterColumnCount", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetClusterColumnCount")
    @ResponseWrapper(localName = "GetClusterColumnCountResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetClusterColumnCountResponse")
    public Integer getClusterColumnCount(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name);

    /**
     * 
     * @param pathDirectionArray
     * @param name
     */
    @WebMethod(operationName = "SetPathDirectionArray", action = "http://tempuri.org/AGVS_IServiceForView/SetPathDirectionArray")
    @Oneway
    @RequestWrapper(localName = "SetPathDirectionArray", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.SetPathDirectionArray")
    public void setPathDirectionArray(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "PathDirectionArray", targetNamespace = "http://tempuri.org/")
        ArrayOfPathDirectionMessage pathDirectionArray);

    /**
     * 
     * @param name
     * @return
     *     returns io.renren.common.agvs.ArrayOfPathDirectionMessage
     */
    @WebMethod(operationName = "GetPathDirectionArray", action = "http://tempuri.org/AGVS_IServiceForView/GetPathDirectionArray")
    @WebResult(name = "GetPathDirectionArrayResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPathDirectionArray", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetPathDirectionArray")
    @ResponseWrapper(localName = "GetPathDirectionArrayResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetPathDirectionArrayResponse")
    public ArrayOfPathDirectionMessage getPathDirectionArray(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name);

    /**
     * 
     * @param pathMessage
     * @param name
     */
    @WebMethod(operationName = "AddPathDirection", action = "http://tempuri.org/AGVS_IServiceForView/AddPathDirection")
    @Oneway
    @RequestWrapper(localName = "AddPathDirection", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddPathDirection")
    public void addPathDirection(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "PathMessage", targetNamespace = "http://tempuri.org/")
        PathDirectionMessage pathMessage);

    /**
     * 
     * @param name
     * @param pathID
     */
    @WebMethod(operationName = "DelPathDirection", action = "http://tempuri.org/AGVS_IServiceForView/DelPathDirection")
    @Oneway
    @RequestWrapper(localName = "DelPathDirection", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelPathDirection")
    public void delPathDirection(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "PathID", targetNamespace = "http://tempuri.org/")
        Integer pathID);

    /**
     * 
     * @param pathMessage
     * @param name
     */
    @WebMethod(operationName = "ModifyPathDirection", action = "http://tempuri.org/AGVS_IServiceForView/ModifyPathDirection")
    @Oneway
    @RequestWrapper(localName = "ModifyPathDirection", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifyPathDirection")
    public void modifyPathDirection(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "PathMessage", targetNamespace = "http://tempuri.org/")
        PathDirectionMessage pathMessage);

    /**
     * 
     * @param name
     * @param station
     */
    @WebMethod(operationName = "AddStation", action = "http://tempuri.org/AGVS_IServiceForView/AddStation")
    @Oneway
    @RequestWrapper(localName = "AddStation", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddStation")
    public void addStation(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "Station", targetNamespace = "http://tempuri.org/")
        StationMessage station);

    /**
     * 
     * @param name
     * @param stationID
     */
    @WebMethod(operationName = "DelStation", action = "http://tempuri.org/AGVS_IServiceForView/DelStation")
    @Oneway
    @RequestWrapper(localName = "DelStation", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelStation")
    public void delStation(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "StationID", targetNamespace = "http://tempuri.org/")
        Integer stationID);

    /**
     * 
     * @param name
     * @param parkID
     * @param stationID
     */
    @WebMethod(operationName = "DelPark", action = "http://tempuri.org/AGVS_IServiceForView/DelPark")
    @Oneway
    @RequestWrapper(localName = "DelPark", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelPark")
    public void delPark(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "StationID", targetNamespace = "http://tempuri.org/")
        Integer stationID,
        @WebParam(name = "ParkID", targetNamespace = "http://tempuri.org/")
        Integer parkID);

    /**
     * 
     * @param name
     * @param station
     */
    @WebMethod(operationName = "ModifyStation", action = "http://tempuri.org/AGVS_IServiceForView/ModifyStation")
    @Oneway
    @RequestWrapper(localName = "ModifyStation", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifyStation")
    public void modifyStation(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "Station", targetNamespace = "http://tempuri.org/")
        StationMessage station);

    /**
     * 
     * @param name
     * @param stationID
     * @return
     *     returns io.renren.common.agvs.StationMessage
     */
    @WebMethod(operationName = "GetStation", action = "http://tempuri.org/AGVS_IServiceForView/GetStation")
    @WebResult(name = "GetStationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStation", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetStation")
    @ResponseWrapper(localName = "GetStationResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetStationResponse")
    public StationMessage getStation(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "StationID", targetNamespace = "http://tempuri.org/")
        Integer stationID);

    /**
     * 
     * @param name
     * @return
     *     returns io.renren.common.agvs.ArrayOfStationMessage
     */
    @WebMethod(operationName = "GetStationArray", action = "http://tempuri.org/AGVS_IServiceForView/GetStationArray")
    @WebResult(name = "GetStationArrayResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStationArray", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetStationArray")
    @ResponseWrapper(localName = "GetStationArrayResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetStationArrayResponse")
    public ArrayOfStationMessage getStationArray(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name);

    /**
     * 
     * @param stationArray
     * @param name
     */
    @WebMethod(operationName = "SetStationArray", action = "http://tempuri.org/AGVS_IServiceForView/SetStationArray")
    @RequestWrapper(localName = "SetStationArray", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.SetStationArray")
    @ResponseWrapper(localName = "SetStationArrayResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.SetStationArrayResponse")
    public void setStationArray(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "StationArray", targetNamespace = "http://tempuri.org/")
        ArrayOfStationMessage stationArray);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "GetStartMode", action = "http://tempuri.org/AGVS_IServiceForView/GetStartMode")
    @WebResult(name = "GetStartModeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStartMode", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetStartMode")
    @ResponseWrapper(localName = "GetStartModeResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetStartModeResponse")
    public Integer getStartMode(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name);

    /**
     * 
     * @param uStyle
     * @param name
     */
    @WebMethod(operationName = "ModifyStartMode", action = "http://tempuri.org/AGVS_IServiceForView/ModifyStartMode")
    @RequestWrapper(localName = "ModifyStartMode", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifyStartMode")
    @ResponseWrapper(localName = "ModifyStartModeResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifyStartModeResponse")
    public void modifyStartMode(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "uStyle", targetNamespace = "http://tempuri.org/")
        Integer uStyle);

    /**
     * 
     * @param bSuspend
     * @param name
     */
    @WebMethod(operationName = "SetbControlCarriers", action = "http://tempuri.org/AGVS_IServiceForView/SetbControlCarriers")
    @RequestWrapper(localName = "SetbControlCarriers", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.SetbControlCarriers")
    @ResponseWrapper(localName = "SetbControlCarriersResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.SetbControlCarriersResponse")
    public void setbControlCarriers(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "bSuspend", targetNamespace = "http://tempuri.org/")
        Boolean bSuspend);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "GetbControlCarriers", action = "http://tempuri.org/AGVS_IServiceForView/GetbControlCarriers")
    @WebResult(name = "GetbControlCarriersResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetbControlCarriers", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetbControlCarriers")
    @ResponseWrapper(localName = "GetbControlCarriersResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetbControlCarriersResponse")
    public Boolean getbControlCarriers(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "GetCarrierSpeed", action = "http://tempuri.org/AGVS_IServiceForView/GetCarrierSpeed")
    @WebResult(name = "GetCarrierSpeedResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCarrierSpeed", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetCarrierSpeed")
    @ResponseWrapper(localName = "GetCarrierSpeedResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetCarrierSpeedResponse")
    public Integer getCarrierSpeed(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name);

    /**
     * 
     * @param name
     * @param speed
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "SetCarrierSpeed", action = "http://tempuri.org/AGVS_IServiceForView/SetCarrierSpeed")
    @WebResult(name = "SetCarrierSpeedResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SetCarrierSpeed", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.SetCarrierSpeed")
    @ResponseWrapper(localName = "SetCarrierSpeedResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.SetCarrierSpeedResponse")
    public Boolean setCarrierSpeed(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "Speed", targetNamespace = "http://tempuri.org/")
        Integer speed);

    /**
     * 
     * @param name
     * @param card
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "AddCard", action = "http://tempuri.org/AGVS_IServiceForView/AddCard")
    @WebResult(name = "AddCardResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddCard", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddCard")
    @ResponseWrapper(localName = "AddCardResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddCardResponse")
    public Boolean addCard(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "Card", targetNamespace = "http://tempuri.org/")
        IOCardData card);

    /**
     * 
     * @param cardID
     * @param name
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DelCard", action = "http://tempuri.org/AGVS_IServiceForView/DelCard")
    @WebResult(name = "DelCardResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DelCard", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelCard")
    @ResponseWrapper(localName = "DelCardResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelCardResponse")
    public Boolean delCard(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "CardID", targetNamespace = "http://tempuri.org/")
        Integer cardID);

    /**
     * 
     * @param name
     * @param card
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "ModifyCard", action = "http://tempuri.org/AGVS_IServiceForView/ModifyCard")
    @WebResult(name = "ModifyCardResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ModifyCard", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifyCard")
    @ResponseWrapper(localName = "ModifyCardResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifyCardResponse")
    public Boolean modifyCard(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "Card", targetNamespace = "http://tempuri.org/")
        IOCardData card);

    /**
     * 
     * @param cardID
     * @param name
     * @return
     *     returns io.renren.common.agvs.IOCardData
     */
    @WebMethod(operationName = "GetCard", action = "http://tempuri.org/AGVS_IServiceForView/GetCard")
    @WebResult(name = "GetCardResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCard", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetCard")
    @ResponseWrapper(localName = "GetCardResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetCardResponse")
    public IOCardData getCard(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "CardID", targetNamespace = "http://tempuri.org/")
        Integer cardID);

    /**
     * 
     * @param name
     * @return
     *     returns io.renren.common.agvs.ArrayOfIOCardData
     */
    @WebMethod(operationName = "GetCardArray", action = "http://tempuri.org/AGVS_IServiceForView/GetCardArray")
    @WebResult(name = "GetCardArrayResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCardArray", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetCardArray")
    @ResponseWrapper(localName = "GetCardArrayResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetCardArrayResponse")
    public ArrayOfIOCardData getCardArray(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name);

    /**
     * 
     * @param name
     * @param equipment
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "AddEquipment", action = "http://tempuri.org/AGVS_IServiceForView/AddEquipment")
    @WebResult(name = "AddEquipmentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddEquipment", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddEquipment")
    @ResponseWrapper(localName = "AddEquipmentResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddEquipmentResponse")
    public Boolean addEquipment(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "Equipment", targetNamespace = "http://tempuri.org/")
        EquipmentData equipment);

    /**
     * 
     * @param name
     * @param equipmentID
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DelEquipment", action = "http://tempuri.org/AGVS_IServiceForView/DelEquipment")
    @WebResult(name = "DelEquipmentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DelEquipment", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelEquipment")
    @ResponseWrapper(localName = "DelEquipmentResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelEquipmentResponse")
    public Boolean delEquipment(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "EquipmentID", targetNamespace = "http://tempuri.org/")
        Integer equipmentID);

    /**
     * 
     * @param name
     * @param equipment
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "ModifyEquipment", action = "http://tempuri.org/AGVS_IServiceForView/ModifyEquipment")
    @WebResult(name = "ModifyEquipmentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ModifyEquipment", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifyEquipment")
    @ResponseWrapper(localName = "ModifyEquipmentResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifyEquipmentResponse")
    public Boolean modifyEquipment(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "Equipment", targetNamespace = "http://tempuri.org/")
        EquipmentData equipment);

    /**
     * 
     * @param name
     * @param equipmentID
     * @return
     *     returns io.renren.common.agvs.EquipmentData
     */
    @WebMethod(operationName = "GetEquipment", action = "http://tempuri.org/AGVS_IServiceForView/GetEquipment")
    @WebResult(name = "GetEquipmentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetEquipment", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetEquipment")
    @ResponseWrapper(localName = "GetEquipmentResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetEquipmentResponse")
    public EquipmentData getEquipment(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "EquipmentID", targetNamespace = "http://tempuri.org/")
        Integer equipmentID);

    /**
     * 
     * @param name
     * @return
     *     returns io.renren.common.agvs.ArrayOfEquipmentData
     */
    @WebMethod(operationName = "GetEquipmentArray", action = "http://tempuri.org/AGVS_IServiceForView/GetEquipmentArray")
    @WebResult(name = "GetEquipmentArrayResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetEquipmentArray", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetEquipmentArray")
    @ResponseWrapper(localName = "GetEquipmentArrayResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetEquipmentArrayResponse")
    public ArrayOfEquipmentData getEquipmentArray(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name);

    /**
     * 
     * @param name
     * @param virtualIO
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "AddIOSwitch", action = "http://tempuri.org/AGVS_IServiceForView/AddIOSwitch")
    @WebResult(name = "AddIOSwitchResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddIOSwitch", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddIOSwitch")
    @ResponseWrapper(localName = "AddIOSwitchResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddIOSwitchResponse")
    public Boolean addIOSwitch(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "VirtualIO", targetNamespace = "http://tempuri.org/")
        IOSwitchData virtualIO);

    /**
     * 
     * @param ioid
     * @param name
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DelIOSwitch", action = "http://tempuri.org/AGVS_IServiceForView/DelIOSwitch")
    @WebResult(name = "DelIOSwitchResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DelIOSwitch", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelIOSwitch")
    @ResponseWrapper(localName = "DelIOSwitchResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelIOSwitchResponse")
    public Boolean delIOSwitch(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "IOID", targetNamespace = "http://tempuri.org/")
        Integer ioid);

    /**
     * 
     * @param name
     * @param virtualIO
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "ModifyIOSwitch", action = "http://tempuri.org/AGVS_IServiceForView/ModifyIOSwitch")
    @WebResult(name = "ModifyIOSwitchResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ModifyIOSwitch", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifyIOSwitch")
    @ResponseWrapper(localName = "ModifyIOSwitchResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifyIOSwitchResponse")
    public Boolean modifyIOSwitch(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "VirtualIO", targetNamespace = "http://tempuri.org/")
        IOSwitchData virtualIO);

    /**
     * 
     * @param ioid
     * @param name
     * @return
     *     returns io.renren.common.agvs.IOSwitchData
     */
    @WebMethod(operationName = "GetIOSwitch", action = "http://tempuri.org/AGVS_IServiceForView/GetIOSwitch")
    @WebResult(name = "GetIOSwitchResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetIOSwitch", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetIOSwitch")
    @ResponseWrapper(localName = "GetIOSwitchResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetIOSwitchResponse")
    public IOSwitchData getIOSwitch(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "IOID", targetNamespace = "http://tempuri.org/")
        Integer ioid);

    /**
     * 
     * @param name
     * @return
     *     returns io.renren.common.agvs.ArrayOfIOSwitchData
     */
    @WebMethod(operationName = "GetIOSwitchArray", action = "http://tempuri.org/AGVS_IServiceForView/GetIOSwitchArray")
    @WebResult(name = "GetIOSwitchArrayResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetIOSwitchArray", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetIOSwitchArray")
    @ResponseWrapper(localName = "GetIOSwitchArrayResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetIOSwitchArrayResponse")
    public ArrayOfIOSwitchData getIOSwitchArray(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name);

    /**
     * 
     * @param par
     * @param name
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "AddStaticOp", action = "http://tempuri.org/AGVS_IServiceForView/AddStaticOp")
    @WebResult(name = "AddStaticOpResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddStaticOp", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddStaticOp")
    @ResponseWrapper(localName = "AddStaticOpResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddStaticOpResponse")
    public Boolean addStaticOp(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "Par", targetNamespace = "http://tempuri.org/")
        StaticOperationParemeters par);

    /**
     * 
     * @param name
     * @param opID
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DelStaticOp", action = "http://tempuri.org/AGVS_IServiceForView/DelStaticOp")
    @WebResult(name = "DelStaticOpResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DelStaticOp", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelStaticOp")
    @ResponseWrapper(localName = "DelStaticOpResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelStaticOpResponse")
    public Boolean delStaticOp(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "OpID", targetNamespace = "http://tempuri.org/")
        Integer opID);

    /**
     * 
     * @param par
     * @param name
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "ModifyStaticOp", action = "http://tempuri.org/AGVS_IServiceForView/ModifyStaticOp")
    @WebResult(name = "ModifyStaticOpResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ModifyStaticOp", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifyStaticOp")
    @ResponseWrapper(localName = "ModifyStaticOpResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifyStaticOpResponse")
    public Boolean modifyStaticOp(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "Par", targetNamespace = "http://tempuri.org/")
        StaticOperationParemeters par);

    /**
     * 
     * @param name
     * @param opid
     * @return
     *     returns io.renren.common.agvs.StaticOperationParemeters
     */
    @WebMethod(operationName = "GetStaticOp", action = "http://tempuri.org/AGVS_IServiceForView/GetStaticOp")
    @WebResult(name = "GetStaticOpResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStaticOp", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetStaticOp")
    @ResponseWrapper(localName = "GetStaticOpResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetStaticOpResponse")
    public StaticOperationParemeters getStaticOp(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "OPID", targetNamespace = "http://tempuri.org/")
        Integer opid);

    /**
     * 
     * @param name
     * @return
     *     returns io.renren.common.agvs.ArrayOfStaticOperationParemeters
     */
    @WebMethod(operationName = "GetStaticOpArray", action = "http://tempuri.org/AGVS_IServiceForView/GetStaticOpArray")
    @WebResult(name = "GetStaticOpArrayResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetStaticOpArray", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetStaticOpArray")
    @ResponseWrapper(localName = "GetStaticOpArrayResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetStaticOpArrayResponse")
    public ArrayOfStaticOperationParemeters getStaticOpArray(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name);

    /**
     * 
     * @param name
     * @param userName
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "FindUserByName", action = "http://tempuri.org/AGVS_IServiceForView/FindUserByName")
    @WebResult(name = "FindUserByNameResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "FindUserByName", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.FindUserByName")
    @ResponseWrapper(localName = "FindUserByNameResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.FindUserByNameResponse")
    public Boolean findUserByName(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "UserName", targetNamespace = "http://tempuri.org/")
        String userName);

    /**
     * 
     * @param name
     * @param userName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetPasswordByName", action = "http://tempuri.org/AGVS_IServiceForView/GetPasswordByName")
    @WebResult(name = "GetPasswordByNameResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPasswordByName", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetPasswordByName")
    @ResponseWrapper(localName = "GetPasswordByNameResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetPasswordByNameResponse")
    public String getPasswordByName(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "UserName", targetNamespace = "http://tempuri.org/")
        String userName);

    /**
     * 
     * @param name
     * @param userName
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "GetRightByName", action = "http://tempuri.org/AGVS_IServiceForView/GetRightByName")
    @WebResult(name = "GetRightByNameResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRightByName", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetRightByName")
    @ResponseWrapper(localName = "GetRightByNameResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetRightByNameResponse")
    public Integer getRightByName(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "UserName", targetNamespace = "http://tempuri.org/")
        String userName);

    /**
     * 
     * @param name
     * @param userID
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DelUser", action = "http://tempuri.org/AGVS_IServiceForView/DelUser")
    @WebResult(name = "DelUserResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DelUser", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelUser")
    @ResponseWrapper(localName = "DelUserResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelUserResponse")
    public Boolean delUser(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "UserID", targetNamespace = "http://tempuri.org/")
        Integer userID);

    /**
     * 
     * @param name
     * @return
     *     returns io.renren.common.agvs.ArrayOfUserData
     */
    @WebMethod(operationName = "GetAllUserArray", action = "http://tempuri.org/AGVS_IServiceForView/GetAllUserArray")
    @WebResult(name = "GetAllUserArrayResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAllUserArray", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetAllUserArray")
    @ResponseWrapper(localName = "GetAllUserArrayResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetAllUserArrayResponse")
    public ArrayOfUserData getAllUserArray(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name);

    /**
     * 
     * @param name
     * @param carrierID
     * @param sleepOrWakeup
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "SetCarrierSleepOrWakeUp", action = "http://tempuri.org/AGVS_IServiceForView/SetCarrierSleepOrWakeUp")
    @WebResult(name = "SetCarrierSleepOrWakeUpResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SetCarrierSleepOrWakeUp", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.SetCarrierSleepOrWakeUp")
    @ResponseWrapper(localName = "SetCarrierSleepOrWakeUpResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.SetCarrierSleepOrWakeUpResponse")
    public Boolean setCarrierSleepOrWakeUp(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "CarrierID", targetNamespace = "http://tempuri.org/")
        Integer carrierID,
        @WebParam(name = "SleepOrWakeup", targetNamespace = "http://tempuri.org/")
        Integer sleepOrWakeup);

    /**
     * 
     * @param op
     * @param name
     * @param carrierID
     */
    @WebMethod(operationName = "SetCarrierPersonOperationData", action = "http://tempuri.org/AGVS_IServiceForView/SetCarrierPersonOperationData")
    @RequestWrapper(localName = "SetCarrierPersonOperationData", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.SetCarrierPersonOperationData")
    @ResponseWrapper(localName = "SetCarrierPersonOperationDataResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.SetCarrierPersonOperationDataResponse")
    public void setCarrierPersonOperationData(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        WorkAreaName name,
        @WebParam(name = "CarrierID", targetNamespace = "http://tempuri.org/")
        Integer carrierID,
        @WebParam(name = "OP", targetNamespace = "http://tempuri.org/")
        Integer op);

    /**
     * 
     * @param sysVersion
     * @param companyID
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "AddSystemControl", action = "http://tempuri.org/AGVS_IServiceForView/AddSystemControl")
    @WebResult(name = "AddSystemControlResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddSystemControl", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddSystemControl")
    @ResponseWrapper(localName = "AddSystemControlResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddSystemControlResponse")
    public Boolean addSystemControl(
        @WebParam(name = "CompanyID", targetNamespace = "http://tempuri.org/")
        Integer companyID,
        @WebParam(name = "SysVersion", targetNamespace = "http://tempuri.org/")
        String sysVersion);

    /**
     * 
     * @param companyID
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DelSystemControl", action = "http://tempuri.org/AGVS_IServiceForView/DelSystemControl")
    @WebResult(name = "DelSystemControlResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DelSystemControl", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelSystemControl")
    @ResponseWrapper(localName = "DelSystemControlResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelSystemControlResponse")
    public Boolean delSystemControl(
        @WebParam(name = "CompanyID", targetNamespace = "http://tempuri.org/")
        Integer companyID);

    /**
     * 
     * @param sysVersion
     * @param companyID
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "ModifySystemControl", action = "http://tempuri.org/AGVS_IServiceForView/ModifySystemControl")
    @WebResult(name = "ModifySystemControlResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ModifySystemControl", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifySystemControl")
    @ResponseWrapper(localName = "ModifySystemControlResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifySystemControlResponse")
    public Boolean modifySystemControl(
        @WebParam(name = "CompanyID", targetNamespace = "http://tempuri.org/")
        Integer companyID,
        @WebParam(name = "SysVersion", targetNamespace = "http://tempuri.org/")
        String sysVersion);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "AddCompany", action = "http://tempuri.org/AGVS_IServiceForView/AddCompany")
    @WebResult(name = "AddCompanyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddCompany", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddCompany")
    @ResponseWrapper(localName = "AddCompanyResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddCompanyResponse")
    public Boolean addCompany(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        Company name);

    /**
     * 
     * @param companyID
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DelCompany", action = "http://tempuri.org/AGVS_IServiceForView/DelCompany")
    @WebResult(name = "DelCompanyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DelCompany", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelCompany")
    @ResponseWrapper(localName = "DelCompanyResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelCompanyResponse")
    public Boolean delCompany(
        @WebParam(name = "CompanyID", targetNamespace = "http://tempuri.org/")
        Integer companyID);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "ModifyCompany", action = "http://tempuri.org/AGVS_IServiceForView/ModifyCompany")
    @WebResult(name = "ModifyCompanyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ModifyCompany", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifyCompany")
    @ResponseWrapper(localName = "ModifyCompanyResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.ModifyCompanyResponse")
    public Boolean modifyCompany(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        Company name);

    /**
     * 
     * @param companyID
     * @return
     *     returns io.renren.common.agvs.Company
     */
    @WebMethod(operationName = "GetCompany", action = "http://tempuri.org/AGVS_IServiceForView/GetCompany")
    @WebResult(name = "GetCompanyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCompany", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetCompany")
    @ResponseWrapper(localName = "GetCompanyResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetCompanyResponse")
    public Company getCompany(
        @WebParam(name = "CompanyID", targetNamespace = "http://tempuri.org/")
        Integer companyID);

    /**
     * 
     * @return
     *     returns io.renren.common.agvs.ArrayOfCompany
     */
    @WebMethod(operationName = "GetAllCompany", action = "http://tempuri.org/AGVS_IServiceForView/GetAllCompany")
    @WebResult(name = "GetAllCompanyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetAllCompany", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetAllCompany")
    @ResponseWrapper(localName = "GetAllCompanyResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.GetAllCompanyResponse")
    public ArrayOfCompany getAllCompany();

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "AddFactory", action = "http://tempuri.org/AGVS_IServiceForView/AddFactory")
    @WebResult(name = "AddFactoryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "AddFactory", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddFactory")
    @ResponseWrapper(localName = "AddFactoryResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.AddFactoryResponse")
    public Boolean addFactory(
        @WebParam(name = "Name", targetNamespace = "http://tempuri.org/")
        Factory name);

    /**
     * 
     * @param companyID
     * @param fatortID
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DelFactory", action = "http://tempuri.org/AGVS_IServiceForView/DelFactory")
    @WebResult(name = "DelFactoryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DelFactory", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelFactory")
    @ResponseWrapper(localName = "DelFactoryResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelFactoryResponse")
    public Boolean delFactory(
        @WebParam(name = "CompanyID", targetNamespace = "http://tempuri.org/")
        Integer companyID,
        @WebParam(name = "FatortID", targetNamespace = "http://tempuri.org/")
        Integer fatortID);

    /**
     * 
     * @param companyID
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "DelAllFactoryInCaompany", action = "http://tempuri.org/AGVS_IServiceForView/DelAllFactoryInCaompany")
    @WebResult(name = "DelAllFactoryInCaompanyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DelAllFactoryInCaompany", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelAllFactoryInCaompany")
    @ResponseWrapper(localName = "DelAllFactoryInCaompanyResponse", targetNamespace = "http://tempuri.org/", className = "io.renren.common.agvs.DelAllFactoryInCaompanyResponse")
    public Boolean delAllFactoryInCaompany(
        @WebParam(name = "CompanyID", targetNamespace = "http://tempuri.org/")
        Integer companyID);

}
