version: '2'
services:
  yanan-admin:
    image: yanan/admin
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=dev
  yanan-api:
    image: yanan/api
    ports:
      - "8081:8081"
    environment:
      - spring.profiles.active=dev